config/routes.rb
AutoMarket::Application.routes.draw do
  resources :manufacturers

  resources :users

  resources :markas
  
  resources :cars

   root :to => 'start_page#home'

end

app/models/marka.rb
# == Schema Information
#
# Table name: markas
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  manufacturer_id :integer
#  year_start      :integer
#  year_end        :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class Marka < ActiveRecord::Base
	validates :manufacturer, presence: true
	belongs_to :manufacturer
  validates :year_start,  presence: true, :format => { :with => /\A[0-9]+\z/, :message => "Only digits allowed" }
	validates_numericality_of :year_end,  presence: true, :greater_than => :year_start, :on => :create	
end

app/controllers/markas_controller.rb
class MarkasController < ApplicationController
  # GET /markas
  # GET /markas.json
  def index
    @markas = Marka.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @markas }
    end
  end

  # GET /markas/1
  # GET /markas/1.json
  def show
    @marka = Marka.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @marka }
    end
  end

  # GET /markas/new
  # GET /markas/new.json
  def new
    @marka = Marka.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @marka }
    end
  end

  # GET /markas/1/edit
  def edit
    @marka = Marka.find(params[:id])
  end

  # POST /markas
  # POST /markas.json
  def create
    @marka = Marka.new(params[:marka])

    respond_to do |format|
      if @marka.save
        format.html { redirect_to @marka, notice: 'Marka was successfully created.' }
        format.json { render json: @marka, status: :created, location: @marka }
      else
        format.html { render action: "new" }
        format.json { render json: @marka.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /markas/1
  # PUT /markas/1.json
  def update
    @marka = Marka.find(params[:id])

    respond_to do |format|
      if @marka.update_attributes(params[:marka])
        format.html { redirect_to @marka, notice: 'Marka was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @marka.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markas/1
  # DELETE /markas/1.json
  def destroy
    @marka = Marka.find(params[:id])
    @marka.destroy

    respond_to do |format|
      format.html { redirect_to markas_url }
      format.json { head :ok }
    end
  end
end

app/helpers/markas_helper.rb
module MarkasHelper
end

app/views/markas/_form.html.erb
<%= form_for(@marka) do |f| %>
  <% if @marka.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@marka.errors.count, "error") %> prohibited this marka from being saved:</h2>

      <ul>
      <% @marka.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :manufacturer_id %><br />
    <% manufacturer_array = Manufacturer.all.map { |man| [man.name, man.id] } %>
    <%= f.select(:manufacturer_id, manufacturer_array) %>
  </div>
  <div class="field">
    <%= f.label :year_start %><br />
    <%= f.number_field :year_start %>
  </div>
  <div class="field">
    <%= f.label :year_end %><br />
    <%= f.number_field :year_end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/markas/edit.html.erb
<h1>Editing marka</h1>

<%= render 'form' %>

<%= link_to 'Show', @marka %> |
<%= link_to 'Back', markas_path %>

app/views/markas/index.html.erb
<h1>Listing markas</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Manufacturer</th>
    <th>Year start</th>
    <th>Year end</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @markas.each do |marka| %>
  <tr>
    <td><%= marka.name %></td>
    <td><%= marka.manufacturer.name%></td>
    <td><%= marka.year_start %></td>
    <td><%= marka.year_end %></td>
    <td><%= link_to 'Show', marka %></td>
    <td><%= link_to 'Edit', edit_marka_path(marka) %></td>
    <td><%= link_to 'Destroy', marka, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Marka', new_marka_path %>

app/views/markas/new.html.erb
<h1>New marka</h1>

<%= render 'form' %>

<%= link_to 'Back', markas_path %>

app/views/markas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @marka.name %>
</p>

<p>
  <b>Manufacturer:</b>
  <%= @marka.manufacturer.name %>
</p>

<p>
  <b>Year start:</b>
  <%= @marka.year_start %>
</p>

<p>
  <b>Year end:</b>
  <%= @marka.year_end %>
</p>


<%= link_to 'Edit', edit_marka_path(@marka) %> |
<%= link_to 'Back', markas_path %>