config/routes.rb
AutoMarket::Application.routes.draw do
  resources :manufacturers

  resources :users

  resources :markas
  
  resources :cars

   root :to => 'start_page#home'

end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#  marka_id   :integer
#

class Car < ActiveRecord::Base
	# Validates
belongs_to :user
validates :user, presence: true
belongs_to :marka
validates :marka, presence: true
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end
  
  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end
  
  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :ok }
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <% user_array = User.all.map { |usr| [usr.first_name, usr.id] } %>
    <%= f.select(:user_id, user_array) %>
  </div>
  <div class="field">
    <%= f.label :marka_id %><br />
    <% marka_array = Marka.all.map { |mod| [mod.name, mod.id] } %>
    <%= f.select(:marka_id, marka_array) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing cars</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
    <th>User</th>
    <th>Marka</th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.user.first_name %></td>
    <td><%= car.marka.name %></td>
    <td><%= link_to 'Show', car %></td>
    <td><%= link_to 'Edit', edit_car_path(car) %></td>
    <td><%= link_to 'Destroy', car, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add new car', new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @car.user.first_name %>
</p>

<p>
  <b>Marka:</b>
  <%= @car.marka.name %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>