config/routes.rb
AutoMarket::Application.routes.draw do
  resources :manufacturers

  resources :users

  resources :markas
  
  resources :cars

   root :to => 'start_page#home'

end

app/models/manufacturer.rb
# == Schema Information
#
# Table name: manufacturers
#
#  id          :integer          not null, primary key
#  created_at  :datetime
#  updated_at  :datetime
#  name        :string(255)
#  country     :string(255)
#  description :text
#

class Manufacturer < ActiveRecord::Base
	# Validates
  has_many :marka
  validates_associated :marka
  validates :name,  presence: true, :format => { :with => /\A[a-zA-Z]+\z/, :message => "Only letters allowed" }
  validates :country,  presence: true, :format => { :with => /\A[a-zA-Z]+\z/, :message => "Only letters allowed" }
  
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  # GET /manufacturers
  # GET /manufacturers.json
  def index
    @manufacturers = Manufacturer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @manufacturers }
    end
  end

  # GET /manufacturers/1
  # GET /manufacturers/1.json
  def show
    @manufacturer = Manufacturer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manufacturer }
    end
  end

  # GET /manufacturers/new
  # GET /manufacturers/new.json
  def new
    @manufacturer = Manufacturer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @manufacturer }
    end
  end

  # GET /manufacturers/1/edit
  def edit
    @manufacturer = Manufacturer.find(params[:id])
  end

  # POST /manufacturers
  # POST /manufacturers.json
  def create
    @manufacturer = Manufacturer.new(params[:manufacturer])

    respond_to do |format|
      if @manufacturer.save
        format.html { redirect_to @manufacturer, notice: 'Manufacturer was successfully created.' }
        format.json { render json: @manufacturer, status: :created, location: @manufacturer }
      else
        format.html { render action: "new" }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /manufacturers/1
  # PUT /manufacturers/1.json
  def update
    @manufacturer = Manufacturer.find(params[:id])

    respond_to do |format|
      if @manufacturer.update_attributes(params[:manufacturer])
        format.html { redirect_to @manufacturer, notice: 'Manufacturer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufacturers/1
  # DELETE /manufacturers/1.json
  def destroy
    @manufacturer = Manufacturer.find(params[:id])
    @manufacturer.destroy

    respond_to do |format|
      format.html { redirect_to manufacturers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/manufacturers/_form.html.erb
<%= form_for(@manufacturer) do |f| %>
  <% if @manufacturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manufacturer.errors.count, "error") %> prohibited this manufacturer from being saved:</h2>

      <ul>
      <% @manufacturer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manufacturers/edit.html.erb
<h1>Editing manufacturer</h1>

<%= render 'form' %>

<%= link_to 'Show', @manufacturer %> |
<%= link_to 'Back', manufacturers_path %>

app/views/manufacturers/index.html.erb
<h1>Listing manufacturers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @manufacturers.each do |manufacturer| %>
  <tr>
    <td><%= manufacturer.name %></td>
    <td><%= manufacturer.country %></td>
    <td><%= manufacturer.description %></td>
    <td><%= link_to 'Show', manufacturer %></td>
    <td><%= link_to 'Edit', edit_manufacturer_path(manufacturer) %></td>
    <td><%= link_to 'Destroy', manufacturer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Manufacturer', new_manufacturer_path %>

app/views/manufacturers/new.html.erb
<h1>New manufacturer</h1>

<%= render 'form' %>

<%= link_to 'Back', manufacturers_path %>

app/views/manufacturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @manufacturer.name %>
</p>

<p>
  <b>Country:</b>
  <%= @manufacturer.country %>
</p>

<p>
  <b>Description:</b>
  <%= @manufacturer.description %>
</p>


<%= link_to 'Edit', edit_manufacturer_path(@manufacturer) %> |
<%= link_to 'Back', manufacturers_path %>